version: "2"
services:
  dongtai-mysql:
    image: "dongtai/dongtai-mysql:{{ DONGTAI_IMAGE_VERSION }}"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "mysql-vol:/var/lib/mysql:rw"
      #- "/var/lib/mysql"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  dongtai-redis:
    image: "dongtai/dongtai-redis:{{ DONGTAI_IMAGE_VERSION }}"
    restart: always
    ports:
      - "6379:6379"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  dongtai-web:
    image: "dongtai/dongtai-web:{{ DONGTAI_IMAGE_VERSION }}"
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
volumes:
  mysql-vol:
