version: "2"
services:
  dongtai-mysql:
    image: registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-mysql:1.4.0
    restart: always
    ports:
      - "33060:3306"
    volumes:
      - "mysql-vol:/var/lib/mysql:rw"
      #- "/var/lib/mysql"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  dongtai-redis:
    image: registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-redis:1.4.0
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  dongtai-webapi:
    image: "registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-webapi:1.4.0"
    restart: always
    volumes:
      - "/home/song/DongTai/deploy/docker-compose/config-tutorial.ini:/opt/dongtai/webapi/conf/config.ini"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    depends_on:
      - dongtai-mysql

  dongtai-web:
    image: "registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-web:1.4.0"
    restart: always
    ports:
      - "83:80"
    volumes:
      - "/home/song/DongTai/deploy/docker-compose/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - dongtai-webapi
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  dongtai-openapi:
    image: "registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-openapi:1.4.0"
    restart: always
    volumes:
       - "/home/song/DongTai/deploy/docker-compose/config-tutorial.ini:/opt/dongtai/openapi/conf/config.ini"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    depends_on:
      - dongtai-mysql

  dongtai-engine:
    image: "registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-engine:1.4.0"
    restart: always
    volumes:
      - "/home/song/DongTai/deploy/docker-compose/config-tutorial.ini:/opt/dongtai/engine/conf/config.ini"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    depends_on:
      - dongtai-mysql

  dongtai-engine-task:
    image: "registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-engine:1.4.0"
    restart: always
    command: ["/opt/dongtai/engine/docker/entrypoint.sh", "task"]
    volumes:
      - "/home/song/DongTai/deploy/docker-compose/config-tutorial.ini:/opt/dongtai/engine/conf/config.ini"
    depends_on:
      - dongtai-engine
      - dongtai-mysql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
volumes:
  mysql-vol:
