version: "2"
services:
  dongtai-mysql: 
    image: registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-mysql:{CHANGE_THIS_VERSION}
    restart: always
    volumes:
      - "mysql-vol:/var/lib/mysql:rw"

  dongtai-redis:
    image: registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-redis:{CHANGE_THIS_VERSION}
    restart: always

  dongtai-web:
    image: registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-web:{CHANGE_THIS_VERSION}
    restart: always
    ports:
      - "8088:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - dongtai-server

  dongtai-engine:
    image: "registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-server:{CHANGE_THIS_VERSION}"
    restart: always
    entrypoint: ["/opt/dongtai/webapi/docker/entrypoint.sh", "worker"]
    volumes:
      - "./config-tutorial.ini:/opt/dongtai/webapi/conf/config.ini"

  dongtai-server:
    image: "registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-server:{CHANGE_THIS_VERSION}"
    restart: always
    volumes:
      - "./config-tutorial.ini:/opt/dongtai/webapi/conf/config.ini"

  dongtai-engine-task:
    image: "registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-server:{CHANGE_THIS_VERSION}"
    restart: always
    entrypoint: ["/opt/dongtai/webapi/docker/entrypoint.sh", "beat"]
    volumes:
      - "./config-tutorial.ini:/opt/dongtai/webapi/conf/config.ini"

  dongtai-vulns:
    image: "dongtai/openrasp-tomcat8:dongtai-java-agent{CHANGE_THIS_VERSION}"
    restart: always
    ports:
      - "8089:8080"
    environment:
      - "JAVA_TOOL_OPTIONS=-javaagent:/opt/agent.jar -Ddongtai.app.name=OpenRASP -Ddongtai.server.url=http://dongtai-web/openapi -Ddongtai.server.token={CHANGE_THIS_TOKEN}"
volumes:
  mysql-vol:
