# This is a basic workflow to help you get started with Actions

name: Deploy DongTai Server To Dev

on:
  push:
    branches: [ "dev*"  ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Deploy-to-dev:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Aliyun Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_DOCKERHUB_USER }}
          password: ${{ secrets.ALIYUN_DOCKERHUB_PASSWORD }}
  
      - name: Setup Ossutil
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: ${{ secrets.ALIYUN_OSS_ENDPOINT }}
          access-key-id: ${{ secrets.ALIYUN_OSS_KEY_ID }}
          access-key-secret: ${{ secrets.ALIYUN_OSS_KEY_SECRET }}
          
      - name: Download Agent
        run: |
          ossutil cp oss://dongtai/agent_test/java/latest/ ./ --include "*.jar" -r
          ossutil cp oss://dongtai/agent_test/python/ ./  --include "*.tar.gz" -r
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          context: .
          push: true
          tags: | 
            registry.cn-beijing.aliyuncs.com/secnium/dongtai-server-dev:latest
            registry.cn-beijing.aliyuncs.com/secnium/dongtai-server-dev:1.0.${{github.run_number}}

      - uses: actions/checkout@master
      - name: deploy to cluster
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DEV_DATA }}
        with:
          args: |
            find .github/deploy/deploy-dongtai-server-dev.yml -type f -exec sed -i 's/VERSION/1.0.${{github.run_number}}/g' {} \;
            ls .github/deploy/deploy-dongtai-server-dev.yml | xargs -I {} kubectl apply -f {}
