name: dtctl-unitest
on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-18.04]
    steps:

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1

      - name: Check out code
        uses: actions/checkout@v1

      - name: UnitTest
        working-directory: deploy/docker-compose
        run: bats test/test_dtctl.bats 